# copy pism config netcdf file to runscript location
always_copy_config: true
# jinja template for the runfile, possible: [PISM_SLURM.sh , PISM_bash.sh]
template_default: PISM_SLURM.sh
# mail address where slurm notes are sent to
slurm_mail: sbeyer@marum.de
# if you use automaticData to generate the setup files, put its path here
automaticData_path: /home/sebi/Nextcloud/palmod/datasets/automaticIceData


